databases:
  - name: prengaconstruction-db
    databaseName: prengaconstruction
    user: prengaconstruction
    plan: free

services:
  - type: web
    name: prengaconstruction
    runtime: python
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate --noinput
    startCommand: python manage.py migrate --noinput && python manage.py restore_projects && gunicorn PrengaConstruction.wsgi:application
    envVars:
      - key: DJANGO_DEBUG
        value: "False"
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: prengaconstruction-db
          property: connectionString